function fullname = getGenBlockName(sys, indicator)
% GETGENBLOCKNAME Gets the name to use for a block in a given system.
%   The point of this function is to be used whenever blocks are generated by
%   the Logic Simplifier Tool in order to ensure some consistency of naming
%   generated blocks across files. Does not check if name is unique.
%
%   Inputs:
%       sys         System in which the block will be generated.
%       indicator   Some string to indicate what the block is. E.g. block type,
%                   operator type, etc.
%
%   Outputs:
%       fullname    Full name (includes path) of block to generate from the
%                   Logic Simplifier.
%

    fullname = [sys '/gen_' indicator];
end