function bool = isSupportedBlockType(blockType)
%
% List of currently supported block types. This is intended primarily for
% reference.

supportedBlockTypes = {...
    'Outport', ...
    'Inport', ...
    'SubSystem', ...
    'Constant', ...
    'Logic', ...
    'RelationalOperator', ...
    'If', ...
    'From'};
% % Upcoming:
%     'Switch', ...
%     'DataStoreRead', ...
%     'Merge' ...
bool = any(strcmp(blockType, supportedBlockTypes));

% The following block types are "supported" in the sense that they do what is
% ultimately wanted, however that just means that they are treated as
% blackbox and there is no intention to handle them differently at present:
%
% {'UnitDelay', 'Delay', 'Deadzone'}
end