function bool = isSupportedBlockType(blockType)
%
% List of currently supported block types. This is intended primarily for
% reference.

supportedBlockTypes = {...
    'Outport', ...
    'Inport', ...
    'SubSystem', ...
    'Constant', ...
    'Logic', ...
    'RelationalOperator'};
bool = any(strcmp(blockType, supportedBlockTypes));
end