function bool = isSupportedBlockType(blockType)
% ISSUPPORTEDBLOCKTYPE Determine is the block type is supported for simplification.
%
%   Inputs:
%       blockType  A block type char array.
%
%   Outputs:
%       bool        1 if supported, otherwise 0.

    % This is the list of currently supported block types. It is intended primarily for
    % reference.
    supportedBlockTypes = {...
        'Outport', ...
        'Inport', ...
        'SubSystem', ...
        'Constant', ...
        'Logic', ... % AND, OR, NAND, NOR, and NOT supported, XOR and NXOR aren't (but don't error still)
        'RelationalOperator', ...
        'If', ...
        'Switch', ...
        'Merge', ...
        'Goto', ...
        'From', ...
        'Ground'};
    bool = any(strcmp(blockType, supportedBlockTypes));

    % The following block types are "supported" in the sense that they do what is
    % ultimately wanted, however that just means that they are treated as
    % blackbox and there is no intention to handle them differently at present:
    %
    % {'UnitDelay', 'Delay', 'Deadzone', 'DataStoreRead'}
end